# Generated by Django 5.1.6 on 2025-03-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercourses',
            name='exam_mark',
            field=models.IntegerField(null=True),
        ),
    ]