# Generated by Django 5.1.6 on 2025-06-11 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_has_exam_usercourses_exam_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('correct_answer', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'api_question',
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Test-Question',
                'verbose_name_plural': 'Test-Questions',
                'db_table': 'api_testquestion',
            },
        ),
        migrations.CreateModel(
            name='UserTestAttemptQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(null=True)),
            ],
            options={
                'verbose_name': 'User-Test-Attempt-Question',
                'verbose_name_plural': 'User-Test-Attempt-Questions',
                'db_table': 'api_usertestattemptquestion',
            },
        ),
        migrations.RemoveField(
            model_name='usertestbestattempt',
            name='test',
        ),
        migrations.RemoveField(
            model_name='usertestbestattempt',
            name='user',
        ),
        migrations.RenameField(
            model_name='usertestattempt',
            old_name='result',
            new_name='percent',
        ),
        migrations.RemoveField(
            model_name='test',
            name='body',
        ),
        migrations.AddField(
            model_name='usertestattempt',
            name='is_best',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_limit',
            field=models.IntegerField(help_text='limit in minutes'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['id'], name='api_course_id_fc19fc_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['creator'], name='api_course_creator_16d1a4_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemodule',
            index=models.Index(fields=['id'], name='api_coursem_id_0bb678_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemodule',
            index=models.Index(fields=['course'], name='api_coursem_course__86cbd5_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemodule',
            index=models.Index(fields=['module'], name='api_coursem_module__fd8894_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['id'], name='api_file_id_d4ba9e_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['creator'], name='api_file_creator_f816c8_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['id'], name='api_module_id_2cec80_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['creator'], name='api_module_creator_fefc81_idx'),
        ),
        migrations.AddIndex(
            model_name='modulefile',
            index=models.Index(fields=['id'], name='api_modulef_id_67a95a_idx'),
        ),
        migrations.AddIndex(
            model_name='modulefile',
            index=models.Index(fields=['module'], name='api_modulef_module__1381de_idx'),
        ),
        migrations.AddIndex(
            model_name='modulefile',
            index=models.Index(fields=['file'], name='api_modulef_file_id_a1f4f6_idx'),
        ),
        migrations.AddIndex(
            model_name='moduletest',
            index=models.Index(fields=['id'], name='api_modulet_id_34c4ee_idx'),
        ),
        migrations.AddIndex(
            model_name='moduletest',
            index=models.Index(fields=['module'], name='api_modulet_module__17a060_idx'),
        ),
        migrations.AddIndex(
            model_name='moduletest',
            index=models.Index(fields=['test'], name='api_modulet_test_id_8ded45_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['id'], name='api_program_id_0d7313_idx'),
        ),
        migrations.AddIndex(
            model_name='programcourse',
            index=models.Index(fields=['id'], name='api_program_id_f920a7_idx'),
        ),
        migrations.AddIndex(
            model_name='programcourse',
            index=models.Index(fields=['program'], name='api_program_program_af6b86_idx'),
        ),
        migrations.AddIndex(
            model_name='programcourse',
            index=models.Index(fields=['course'], name='api_program_course__ff2a26_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['id'], name='api_role_id_faeeca_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['id'], name='api_test_id_0ddb05_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['creator'], name='api_test_creator_b92359_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id'], name='api_user_id_9a3b95_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='api_user_email_a7eefd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='api_user_role_id_2c77f2_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourses',
            index=models.Index(fields=['id'], name='api_usercou_id_910b74_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourses',
            index=models.Index(fields=['user'], name='api_usercou_user_id_4c6a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourses',
            index=models.Index(fields=['course'], name='api_usercou_course__c20df6_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestattempt',
            index=models.Index(fields=['id'], name='api_usertes_id_524695_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestattempt',
            index=models.Index(fields=['user'], name='api_usertes_user_id_7d8a99_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestattempt',
            index=models.Index(fields=['test'], name='api_usertes_test_id_ca53c2_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestattempt',
            index=models.Index(fields=['user', 'test'], name='api_usertes_user_id_a5f8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestattempt',
            index=models.Index(fields=['user', 'test', 'is_best'], name='api_usertes_user_id_9a9a40_idx'),
        ),
        migrations.AlterModelTable(
            name='course',
            table='api_course',
        ),
        migrations.AlterModelTable(
            name='coursemodule',
            table='api_coursemodule',
        ),
        migrations.AlterModelTable(
            name='file',
            table='api_file',
        ),
        migrations.AlterModelTable(
            name='module',
            table='api_module',
        ),
        migrations.AlterModelTable(
            name='modulefile',
            table='api_modulefile',
        ),
        migrations.AlterModelTable(
            name='moduletest',
            table='api_moduletest',
        ),
        migrations.AlterModelTable(
            name='program',
            table='api_program',
        ),
        migrations.AlterModelTable(
            name='programcourse',
            table='api_programcourse',
        ),
        migrations.AlterModelTable(
            name='role',
            table='api_role',
        ),
        migrations.AlterModelTable(
            name='test',
            table='api_test',
        ),
        migrations.AlterModelTable(
            name='user',
            table='api_user',
        ),
        migrations.AlterModelTable(
            name='usercourses',
            table='api_usercourses',
        ),
        migrations.AlterModelTable(
            name='usertestattempt',
            table='api_usertestattempt',
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['id'], name='api_questio_id_9e93c2_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['type'], name='api_questio_type_de22f4_idx'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.test'),
        ),
        migrations.AddField(
            model_name='usertestattemptquestion',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usertestattempt'),
        ),
        migrations.AddField(
            model_name='usertestattemptquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
        migrations.DeleteModel(
            name='UserTestBestAttempt',
        ),
        migrations.AddIndex(
            model_name='testquestion',
            index=models.Index(fields=['id'], name='api_testque_id_4dc185_idx'),
        ),
        migrations.AddIndex(
            model_name='testquestion',
            index=models.Index(fields=['test'], name='api_testque_test_id_d1f21d_idx'),
        ),
        migrations.AddIndex(
            model_name='testquestion',
            index=models.Index(fields=['question'], name='api_testque_questio_9f32b6_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestattemptquestion',
            index=models.Index(fields=['attempt'], name='api_usertes_attempt_3ab983_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestattemptquestion',
            index=models.Index(fields=['question'], name='api_usertes_questio_d43564_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestattemptquestion',
            index=models.Index(fields=['attempt', 'question'], name='api_usertes_attempt_7c9400_idx'),
        ),
    ]