# Generated by Django 5.1.6 on 2025-06-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_question_testquestion_usertestattemptquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(default='name', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(unique=True, upload_to='courses/'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file'], name='api_file_file_907cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file_name'], name='api_file_file_na_1ec46a_idx'),
        ),
    ]
