# Generated by Django 5.1.6 on 2025-06-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_file_file_name_alter_file_description_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='coursemodule',
            name='api_coursem_course__86cbd5_idx',
        ),
        migrations.RemoveIndex(
            model_name='coursemodule',
            name='api_coursem_module__fd8894_idx',
        ),
        migrations.RenameField(
            model_name='coursemodule',
            old_name='course',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='coursemodule',
            old_name='module',
            new_name='module_id',
        ),
        migrations.AddIndex(
            model_name='coursemodule',
            index=models.Index(fields=['course_id'], name='api_coursem_course__73143f_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemodule',
            index=models.Index(fields=['module_id'], name='api_coursem_module__da603d_idx'),
        ),
    ]
