# Generated by Django 5.1.6 on 2025-06-17 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_coursemodule_api_coursem_course__86cbd5_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodule',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='coursemodule',
            old_name='module_id',
            new_name='module',
        ),
        migrations.RenameIndex(
            model_name='coursemodule',
            new_name='api_coursem_course__86cbd5_idx',
            old_name='api_coursem_course__73143f_idx',
        ),
        migrations.RenameIndex(
            model_name='coursemodule',
            new_name='api_coursem_module__fd8894_idx',
            old_name='api_coursem_module__da603d_idx',
        ),
    ]
