# Generated by Django 5.1.6 on 2025-06-17 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_course_id_coursemodule_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
        migrations.RenameField(
            model_name='coursemodule',
            old_name='course',
            new_name='course_id',
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='module',
            field=models.ForeignKey(db_column='module_id', on_delete=django.db.models.deletion.CASCADE, to='api.module'),
        ),
        migrations.RenameField(
            model_name='coursemodule',
            old_name='module',
            new_name='module_id',
        ),
    ]
