# Generated by Django 5.1.6 on 2025-06-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_coursemodule_course_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursemodule',
            unique_together={('course_id', 'module_id')},
        ),
    ]
