# Generated by Django 5.1.6 on 2025-06-18 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_coursemodule_unique_together'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='programcourse',
            name='api_program_program_af6b86_idx',
        ),
        migrations.RemoveIndex(
            model_name='programcourse',
            name='api_program_course__ff2a26_idx',
        ),
        migrations.AlterField(
            model_name='programcourse',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
        migrations.RenameField(
            model_name='programcourse',
            old_name='course',
            new_name='course_id',
        ),
        migrations.AlterField(
            model_name='programcourse',
            name='program',
            field=models.ForeignKey(db_column='program_id', on_delete=django.db.models.deletion.CASCADE, to='api.program'),
        ),
        migrations.RenameField(
            model_name='programcourse',
            old_name='program',
            new_name='program_id',
        ),
        migrations.AddIndex(
            model_name='programcourse',
            index=models.Index(fields=['program_id'], name='api_program_program_af6b86_idx'),
        ),
        migrations.AddIndex(
            model_name='programcourse',
            index=models.Index(fields=['course_id'], name='api_program_course__ff2a26_idx'),
        ),
    ]
