# Generated by Django 5.1.6 on 2025-06-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_programcourse_api_program_program_af6b86_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('one', 'Один ответ'), ('multi', 'Несколько ответов'), ('text', 'Строка'), ('table', 'Таблица')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('text', 'type', 'payload', 'correct_answer')},
        ),
    ]
