# Generated by Django 5.1.6 on 2025-06-18 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_question_payload_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='testquestion',
            name='api_testque_test_id_d1f21d_idx',
        ),
        migrations.RemoveIndex(
            model_name='testquestion',
            name='api_testque_questio_9f32b6_idx',
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='question',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
        migrations.RenameField(
            model_name='testquestion',
            old_name='question',
            new_name='question_id',
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='test',
            field=models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.CASCADE, to='api.test'),
        ),
        migrations.RenameField(
            model_name='testquestion',
            old_name='test',
            new_name='test_id',
        ),
        migrations.AlterUniqueTogether(
            name='testquestion',
            unique_together={('test_id', 'question_id')},
        ),
        migrations.AddIndex(
            model_name='testquestion',
            index=models.Index(fields=['test_id'], name='api_testque_test_id_d1f21d_idx'),
        ),
        migrations.AddIndex(
            model_name='testquestion',
            index=models.Index(fields=['question_id'], name='api_testque_questio_9f32b6_idx'),
        ),
    ]
