# Generated by Django 5.1.6 on 2025-06-21 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_testquestion_api_testque_test_id_d1f21d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='has_exam',
        ),
        migrations.AddField(
            model_name='course',
            name='exam_question_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='time_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='test_question_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usertestattempt',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='program',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
