# Generated by Django 5.1.6 on 2025-06-21 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_course_has_exam_course_exam_question_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourses',
            name='exam_mark',
        ),
        migrations.CreateModel(
            name='UserExamAttempt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('percent', models.FloatField(default=0)),
                ('exam_mark', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User-Exam-Attempt',
                'verbose_name_plural': 'User-Exam-Attempts',
                'db_table': 'api_userexamattempt',
            },
        ),
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
                ('test_attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usertestattempt')),
                ('exam_attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userexamattempt')),
            ],
            options={
                'verbose_name': 'Attempt-Question',
                'verbose_name_plural': 'Attempt-Questions',
                'db_table': 'api_attemptquestion',
            },
        ),
        migrations.DeleteModel(
            name='UserTestAttemptQuestion',
        ),
        migrations.AddIndex(
            model_name='userexamattempt',
            index=models.Index(fields=['user'], name='api_userexa_user_id_968909_idx'),
        ),
        migrations.AddIndex(
            model_name='userexamattempt',
            index=models.Index(fields=['course'], name='api_userexa_course__6a3cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='userexamattempt',
            index=models.Index(fields=['user', 'course'], name='api_userexa_user_id_a2a3d5_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptquestion',
            index=models.Index(fields=['test_attempt'], name='api_attempt_test_at_edf66a_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptquestion',
            index=models.Index(fields=['exam_attempt'], name='api_attempt_exam_at_bf8cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptquestion',
            index=models.Index(fields=['question'], name='api_attempt_questio_d45f94_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptquestion',
            index=models.Index(fields=['test_attempt', 'question'], name='api_attempt_test_at_e01e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptquestion',
            index=models.Index(fields=['exam_attempt', 'question'], name='api_attempt_exam_at_db3b42_idx'),
        ),
    ]
