# Generated by Django 5.1.6 on 2025-06-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_usercourses_exam_mark_userexamattempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptquestion',
            name='user_answer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
