# Generated by Django 5.1.6 on 2025-07-06 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_attemptquestion_user_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('progress', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'User-Course',
                'verbose_name_plural': 'User-Courses',
                'db_table': 'api_usercourse',
            },
        ),
        migrations.RemoveField(
            model_name='usercourses',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usercourses',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='attemptquestion',
            name='api_attempt_test_at_edf66a_idx',
        ),
        migrations.RemoveIndex(
            model_name='attemptquestion',
            name='api_attempt_exam_at_bf8cb2_idx',
        ),
        migrations.RemoveIndex(
            model_name='attemptquestion',
            name='api_attempt_test_at_e01e4f_idx',
        ),
        migrations.RemoveIndex(
            model_name='attemptquestion',
            name='api_attempt_exam_at_db3b42_idx',
        ),
        migrations.RemoveIndex(
            model_name='modulefile',
            name='api_modulef_module__1381de_idx',
        ),
        migrations.RemoveIndex(
            model_name='modulefile',
            name='api_modulef_file_id_a1f4f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='moduletest',
            name='api_modulet_module__17a060_idx',
        ),
        migrations.RemoveIndex(
            model_name='moduletest',
            name='api_modulet_test_id_8ded45_idx',
        ),
        migrations.RemoveIndex(
            model_name='userexamattempt',
            name='api_userexa_user_id_968909_idx',
        ),
        migrations.RemoveIndex(
            model_name='userexamattempt',
            name='api_userexa_course__6a3cb8_idx',
        ),
        migrations.RemoveIndex(
            model_name='userexamattempt',
            name='api_userexa_user_id_a2a3d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='usertestattempt',
            name='api_usertes_user_id_7d8a99_idx',
        ),
        migrations.RemoveIndex(
            model_name='usertestattempt',
            name='api_usertes_test_id_ca53c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='usertestattempt',
            name='api_usertes_user_id_a5f8c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='usertestattempt',
            name='api_usertes_user_id_9a9a40_idx',
        ),
        migrations.AlterField(
            model_name='attemptquestion',
            name='exam_attempt',
            field=models.ForeignKey(db_column='exam_attempt_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userexamattempt'),
        ),
        migrations.RenameField(
            model_name='attemptquestion',
            old_name='exam_attempt',
            new_name='exam_attempt_id',
        ),
        migrations.AlterField(
            model_name='attemptquestion',
            name='test_attempt',
            field=models.ForeignKey(db_column='test_attempt_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usertestattempt'),
        ),
        migrations.RenameField(
            model_name='attemptquestion',
            old_name='test_attempt',
            new_name='test_attempt_id',
        ),
        migrations.AlterField(
            model_name='modulefile',
            name='file',
            field=models.ForeignKey(db_column='file_id', on_delete=django.db.models.deletion.CASCADE, to='api.file'),
        ),
        migrations.RenameField(
            model_name='modulefile',
            old_name='file',
            new_name='file_id',
        ),
        migrations.AlterField(
            model_name='modulefile',
            name='module',
            field=models.ForeignKey(db_column='module_id', on_delete=django.db.models.deletion.CASCADE, to='api.module'),
        ),
        migrations.RenameField(
            model_name='modulefile',
            old_name='module',
            new_name='module_id',
        ),
        migrations.AlterField(
            model_name='moduletest',
            name='module',
            field=models.ForeignKey(db_column='module_id', on_delete=django.db.models.deletion.CASCADE, to='api.module'),
        ),
        migrations.RenameField(
            model_name='moduletest',
            old_name='module',
            new_name='module_id',
        ),
        migrations.AlterField(
            model_name='moduletest',
            name='test',
            field=models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.CASCADE, to='api.test'),
        ),
        migrations.RenameField(
            model_name='moduletest',
            old_name='test',
            new_name='test_id',
        ),
        migrations.AlterField(
            model_name='userexamattempt',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
        migrations.RenameField(
            model_name='userexamattempt',
            old_name='course',
            new_name='course_id',
        ),
        migrations.AlterField(
            model_name='userexamattempt',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='userexamattempt',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='usertestattempt',
            name='test',
            field=models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.CASCADE, to='api.test'),
        ),
        migrations.RenameField(
            model_name='usertestattempt',
            old_name='test',
            new_name='test_id',
        ),
        migrations.AlterField(
            model_name='usertestattempt',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='usertestattempt',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddIndex(
            model_name='attemptquestion',
            index=models.Index(fields=['test_attempt_id'], name='api_attempt_test_at_edf66a_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptquestion',
            index=models.Index(fields=['exam_attempt_id'], name='api_attempt_exam_at_bf8cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptquestion',
            index=models.Index(fields=['test_attempt_id', 'question'], name='api_attempt_test_at_e01e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptquestion',
            index=models.Index(fields=['exam_attempt_id', 'question'], name='api_attempt_exam_at_db3b42_idx'),
        ),
        migrations.AddIndex(
            model_name='modulefile',
            index=models.Index(fields=['module_id'], name='api_modulef_module__1381de_idx'),
        ),
        migrations.AddIndex(
            model_name='modulefile',
            index=models.Index(fields=['file_id'], name='api_modulef_file_id_a1f4f6_idx'),
        ),
        migrations.AddIndex(
            model_name='moduletest',
            index=models.Index(fields=['module_id'], name='api_modulet_module__17a060_idx'),
        ),
        migrations.AddIndex(
            model_name='moduletest',
            index=models.Index(fields=['test_id'], name='api_modulet_test_id_8ded45_idx'),
        ),
        migrations.AddIndex(
            model_name='userexamattempt',
            index=models.Index(fields=['user_id'], name='api_userexa_user_id_968909_idx'),
        ),
        migrations.AddIndex(
            model_name='userexamattempt',
            index=models.Index(fields=['course_id'], name='api_userexa_course__6a3cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='userexamattempt',
            index=models.Index(fields=['user_id', 'course_id'], name='api_userexa_user_id_a2a3d5_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestattempt',
            index=models.Index(fields=['user_id'], name='api_usertes_user_id_7d8a99_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestattempt',
            index=models.Index(fields=['test_id'], name='api_usertes_test_id_ca53c2_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestattempt',
            index=models.Index(fields=['user_id', 'test_id'], name='api_usertes_user_id_a5f8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestattempt',
            index=models.Index(fields=['user_id', 'test_id', 'is_best'], name='api_usertes_user_id_9a9a40_idx'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserCourses',
        ),
        migrations.AddIndex(
            model_name='usercourse',
            index=models.Index(fields=['id'], name='api_usercou_id_133f39_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourse',
            index=models.Index(fields=['user_id'], name='api_usercou_user_id_1e53da_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourse',
            index=models.Index(fields=['course_id'], name='api_usercou_course__3ed4ba_idx'),
        ),
    ]
